name = "HeterogeneousArrays"
uuid = "40d36c5c-e028-4551-8108-c37812a952b9"
version = "0.1.0"
authors = ["Gregor Decristoforo <gregor.decristoforo@gmail.com>"]

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Documenter = "1.17.0"
RecursiveArrayTools = "3.48.0"
Unitful = "1.28.0"
